spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_db01?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: microservice-provider
server:
  port: 8888
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatisConfig.xml
  type-aliases-package: com.raindrop.entity
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:6001/eureka/,http://localhost:6002/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}-hystrix
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: [hystrix.stream,bus-refresh]
this:
  name: bill
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_db02?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: microservice-provider

server:
  port: 8888
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatisConfig.xml
  type-aliases-package: com.raindrop.entity
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:6001/eureka/,http://localhost:6002/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}-hystrix
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
